"""Sync check

Revision ID: 69ffd3cc2c7d
Revises: 0600bf989cf4
Create Date: 2026-03-28 15:01:27.237103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69ffd3cc2c7d'
down_revision: Union[str, None] = '0600bf989cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'setup_password_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_users_setup_password_token', table_name='users')
    op.create_index(op.f('ix_users_setup_password_token'), 'users', ['setup_password_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_setup_password_token'), table_name='users')
    op.create_index('ix_users_setup_password_token', 'users', ['setup_password_token'], unique=False)
    op.alter_column('users', 'setup_password_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
